server:
  port: 8080
  error:
    include-exception: true
    include-message: always

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

basePath: /Users/kangdonghoon/github/http-file-server/test-data